### ISSUE TITLE
ヘッダーコンポーネントのスタイル修正（追加）

### ISSUE THREAD

**Issue by yuuugaaa** [Doer-org/hack-camp_vol4_2023-2#65]
@Saki-299 さん
`padding`の変更に伴い、他の箇所もいくつか変更必要そうなので修正お願いします！

# タスク1
`client/src/ui/header/styles/header.css.ts`内に`height`の値も設定されています。

`padding`の変更に併せて、以下の部分の`height`の値を`78px`から`66px`に修正してください。
※`18px`→`12px`のため、`-6px`×2（上下）
```
export const size = styleVariants({
  small: { height: "78px" },
});
```

# ~~タスク2~~
~~`client/src/app/_ui/profile-header/styles/profile-header.css.ts`内に、プロフィールページ固有のヘッダーのスタイルが定義されています。そのうち、以下の部分の`margin`も`18px`から`12px`に修正してください。~~
~~※プロフィール画像とフォローフォロワーの間の余白部分~~
```
export const followWrapperStyle = style({
  marginTop: "18px",
});
```

# 備考
前回やった変更の流れと同じ様に行ってみてください！
よろしくお願いします！

[Figma](https://www.figma.com/file/Ov4IA2Vimhe4kLJi8SifMG/%E6%8A%80%E8%82%B2camp_vol4_2023_2?type=design&node-id=0-1)

**Comment by RyushiAok** [comment]
@Saki-299 タスク1のみでOKです！
